ec_site/account/urls.py
from django.urls import path

from account import views as account_v

app_name = 'account'
urlpatterns = [
    path('login/', account_v.Login.as_view(), name='login'),
    path('logout/', account_v.Logout.as_view(), name='logout'),
    path('signup/', account_v.SignUp.as_view(), name='signup'),
    path('signup/done/', account_v.SignUpDone.as_view(), name='signupdone'),
]

ec_site/book/urls.py
from django.urls import path
from book import views as book_v

app_name = 'book'
urlpatterns = [
    path('detail/<int:pk>/', book_v.BookDetail.as_view(), name='detail'),
]

ec_site/conf/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('store.urls')),
    path('account/', include('account.urls')),
    path('book/', include('book.urls')),
    path('admin/', admin.site.urls),
    path('goods/', include('goods.urls')),

]

ec_site/store/urls.py
from django.urls import path
from store import views as store_v

app_name = 'store'
urlpatterns = [
    path('', store_v.Home.as_view(), name='home'),
    path('add_sessioncart/', store_v.SessionAddToCart.as_view(), name='add_sessioncart'),
    path('sessioncontent/', store_v.SessionCartContent.as_view(), name='sessioncart_content'),
    path('add_modelcart/', store_v.ModelAddToCart.as_view(), name='add_modelcart'),
    path('modelcontent/<int:pk>/', store_v.ModelCartContent.as_view(), name='modelcart_content'), # pk は CartUnitのpk
    path('delete_modelcart/', store_v.ModelCartDelete.as_view(), name='modelcart_delete'),
    path('delete_sessioncart/', store_v.SessionCartDelete.as_view(), name='sessioncart_delete'),
    path('purchase/preview/', store_v.PurchasePreview.as_view(), name='purchase_preview'),
    path('purchase/_process/', store_v.PurchaseProcess.as_view(), name='_purchase_process'),
    path('purchase/done/', store_v.PurchaseDone.as_view(), name='purchase_done'),
]

ec_site/templates/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <link rel="stylesheet" href="style.css"/>
    <title>{% block title %}Python講座{% endblock %}</title>
</head>

<body>
<div id="topbar">
    {% block topbar %}
        <a href="{% url 'store:home' %}">Home</a>

        {% if user.is_authenticated %}
            現在{{ user.username }}でログインしています。
            <a href="{% url 'account:logout' %}">ログアウト</a>
            <a href="{% url 'store:modelcart_content' user.pk %}">カート</a>
        {% else %}
            <a href="{% url 'account:login' %}">ログイン</a>
            <a href="{% url 'account:signup' %}">新規登録</a>
            <a href="{% url 'store:sessioncart_content' %}">カート</a>
        {% endif %}
        <hr>
    {% endblock %}
</div>

<div id="content">
    {% block content %}{% endblock %}
</div>
</body>
</html>