tv_listing/conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tvasahi.urls')),
    path('store/', include('store.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tv_listing/store/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required


app_name = 'store'

urlpatterns = [
    path('home/', views.Home.as_view(), name='home'),
    path('detail/<int:pk>/', login_required(views.GoodsDetail.as_view()), name='detail'),
    path('add_sessioncart/', views.SessionAddToCart.as_view(), name='add_sessioncart'),
    path('sessioncontent/', views.SessionCartContent.as_view(), name='sessioncart_content'),
    path('add_modelcart/', views.ModelAddToCart.as_view(), name='add_modelcart'),
    path('modelcontent/<int:pk>/', views.ModelCartContent.as_view(), name='modelcart_content'), # pk は CartUnitのpk
    path('delete_modelcart/', views.ModelCartDelete.as_view(), name='modelcart_delete'),
    path('delete_sessioncart/', views.SessionCartDelete.as_view(), name='sessioncart_delete'),
    path('purchase/preview/', views.PurchasePreview.as_view(), name='purchase_preview'),
    path('purchase/_process/', views.PurchaseProcess.as_view(), name='_purchase_process'),
    path('purchase/done/', views.PurchaseDone.as_view(), name='purchase_done'),
]

tv_listing/tvasahi/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required


app_name = 'tvasahi'

urlpatterns = [
    path('home/', views.Home.as_view(), name='home'),
    path('tvlist/<int:pk>/', views.TvListView.as_view(), name='tv_list'),
    path('tvdetail/<int:pk>/', views.TvDetailView.as_view(), name='tv_detail'),
    path('tvsearch/', views.SearchView.as_view(), name='tv_search'),
    path('comment_create/<int:pk>/', login_required(views.CommentCreateView.as_view()), name='comment_create'),
    path('login/', views.Login.as_view(), name='login'),
    path('user_create/', views.CustomUserCreationView.as_view(), name='user_create'),
    path('mypage/<int:pk>/', views.MyPage.as_view(), name='mypage'),
    path('user_update/<int:pk>/', views.UserUpdate.as_view(), name='user_update'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('user_delete/<int:pk>/', views.CustomUserDeleteView.as_view(), name='user_delete'),
    path('comment_delete/<int:pk>/', views.CommentDeleteView.as_view(), name='comment_delete'),
    path('comment_delete2/<int:pk>/', views.CommentDeleteView2.as_view(), name='comment_delete2')

    ]

tv_listing/tvasahi/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from django.contrib.auth import get_user_model
from django.conf import settings


class Date(models.Model):
    on_air_date = models.CharField(verbose_name='放送日', max_length=255)

    def __str__(self):
        return self.on_air_date

    class Meta:
        verbose_name = "放送日"
        verbose_name_plural = "放送日"


class Category(models.Model):
    category_name = models.CharField('カテゴリー', max_length=255)

    def __str__(self):
        return self.category_name

    class Meta:
        verbose_name = "カテゴリー"
        verbose_name_plural = "カテゴリー"


class Tv(models.Model):
    program_name = models.CharField('番組名', max_length=255)
    time = models.CharField('放送時間', max_length=25)
    content = models.TextField('番組内容')
    url = models.URLField('番組サイト', null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.PROTECT, verbose_name='カテゴリ')
    date = models.ForeignKey(Date, on_delete=models.PROTECT, verbose_name='放送日')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def get_time_hour_and_minute(self):
        return self.time[:5]

    class Meta:
        verbose_name = "番組タイトル"
        verbose_name_plural = "番組タイトル"

    def __str__(self):
        return self.program_name


class Comment(models.Model):
    user_name = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='ユーザー名')
    comment = models.TextField('コメント内容')
    # target = models.ForeignKey(Tv, on_delete=models.PROTECT, verbose_name='紐付く番組名')
    target = models.ForeignKey(Tv, on_delete=models.CASCADE, verbose_name='紐付く番組名')
    # 登録日時
    pub_date = models.DateTimeField('登録日時', auto_now_add=True)

    def __str__(self):
        return self.comment[:20]

    class Meta:
        verbose_name = "コメント"
        verbose_name_plural = "コメント"


class CustomUser(AbstractUser):
    icon = models.ImageField('アイコン画像', null=True, blank=True, upload_to='icon_images/')
    email = models.EmailField('メールアドレス', unique=True)
    address = models.CharField('住所', max_length=64, blank=False, null=False)
    favorite_category = models.ForeignKey(Category, on_delete=models.PROTECT, verbose_name='好きな番組カテゴリ', null=True)
    cart = models.OneToOneField(to='store.Cart', verbose_name='カート', on_delete=models.CASCADE, blank=True, null=True)

tv_listing/tvasahi/forms.py
from django import forms
from .models import Comment, Category, CustomUser
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("comment",)


class CommentUpdateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("comment",)


class SearchForm(forms.Form):
    keyword = forms.CharField(label='キーワード', required=False)
    category = forms.ModelChoiceField(queryset=Category.objects.all(), label='カテゴリー', required=False,
                                      empty_label='選択してください')


class CustomUserCreationForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].error_messages = {'required': 'パスワードが空です'}
        self.fields['password2'].error_messages = {'required': 'パスワードが空です'}

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError(
                'パスワードが一致しません',
                code="password_mismatch",
            )
        return password2

    class Meta:
        model = CustomUser

        fields = ('username', 'email', 'address', 'favorite_category', 'icon')

        error_messages = {
            'username': {
                'required': "ユーザー名を入力してください。",
            },
            'email': {
                'required': "メールアドレスを入力してください。",
                'invalid': "メールアドレスの形式が不適切です。",
                'unique': "このメールアドレスは既に使用されています。"
            },
            'address': {
                'required': "住所を入力してください。",
            },
            'favorite_category': {
                'required': "カテゴリーを入力してください。",
            },

        }


class UserUpdateForm(forms.ModelForm):
    """ユーザー情報更新フォーム"""

    class Meta:
        model = CustomUser

        fields = ('username', 'email', 'address', 'favorite_category', 'icon')

        error_messages = {
            'username': {
                'required': "ユーザー名を入力してください。",
            },
            'email': {
                'required': "メールアドレスを入力してください。",
                'invalid': "メールアドレスの形式が不適切です。",
                'unique': "このメールアドレスは既に使用されています。"
            },
            'address': {
                'required': "住所を入力してください。",
            },
            'favorite_category': {
                'required': "カテゴリーを入力してください。",
            },
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    # def clean_username(self):
    #     username = self.cleaned_data['username']

tv_listing/tvasahi/views.py
from django.shortcuts import render, redirect, resolve_url
from django.views import generic
from django.urls import reverse_lazy
from .forms import CommentCreateForm, CommentUpdateForm, SearchForm, CustomUserCreationForm, UserUpdateForm
from .models import Tv, Date, Comment, CustomUser
from django.db.models import Q

# ログインとログアウト
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic.base import TemplateView

# マイページ
from django.contrib.auth import get_user_model, logout, login, authenticate  # 追加
from django.contrib.auth.mixins import UserPassesTestMixin  # 追加
from django.contrib import messages
from django.contrib.auth.decorators import login_required


# # Create your views here.
#
#
class Home(generic.ListView):
    model = Date
    template_name = 'tvasahi/home.html'

    def get_context_data(self):
        context = super().get_context_data()
        date = Date.objects.get(on_air_date='6/30')
        tv_list = Tv.objects.filter(date=date)
        context['tv_list'] = tv_list
        return context


def a(obj):
    hour_and_minits = obj.time.split(':')
    hour = hour_and_minits[0]
    minits = hour_and_minits[1]
    return int(hour), int(minits)


class TvListView(generic.ListView):
    model = Tv
    template_name = 'tvasahi/tv_list.html'

    def get_context_data(self):
        context = {}
        queryset = Tv.objects.all()
        date = Date.objects.get(pk=self.kwargs['pk'])
        queryset = queryset.filter(date=date)
        queryset = list(queryset)
        # 昇順
        queryset.sort(key=a)
        # 降順
        # queryset.sort(key=a, reverse=True)
        context['tv_list'] = queryset

        date_list = Date.objects.all()
        context['date_list'] = date_list

        return context


class TvListHomeView(generic.ListView):
    model = Tv
    template_name = 'tvasahi/home.html'

    # def get_queryset(self):
    #     queryset = super().get_queryset()
    #     date = Date.objects.get(pk=self.kwargs['pk'])
    #     queryset = queryset.filter(date=date)
    #     return queryset


class TvDetailView(generic.DetailView):
    model = Tv
    template_name = 'tvasahi/tv_detail.html'


class CommentCreateView(generic.CreateView):
    model = Comment
    template_name = 'tvasahi/comment_create.html'
    form_class = CommentCreateForm
    success_url = reverse_lazy('tvasahi:tv_detail')

    def form_valid(self, form):
        # form.save(commit=False) データベースにはまだ保存しない
        # commit=False　ビューでモデルのフィールドを埋めるために使う引数
        comment = form.save(commit=False)
        comment.user_name = self.request.user

        # commentモデルのtargetフィールドをここで埋める
        # モデル名.objects.get(フィールド=値) 1つだけDBから取り出すのに使うメソッドがget
        # url内の<int:pk>はself.kwargs['pk']で取得できる
        comment.target = Tv.objects.get(pk=self.kwargs['pk'])

        # 上2行をまとめてこう書かれている場合も多い
        # form.instance.target = Article.objects.get(pk=self.kwargs['pk'])

        comment.save()
        return redirect('tvasahi:tv_detail', self.kwargs['pk'])





"""
class CommentListView(generic.ListView):
    model = Comment
    template_name = 'tvasahi/mypage.html'
    
class CommentUpdateView(generic.UpdateView):

"""


# class CommentDeleteView(generic.DeleteView):
#     model = Comment
#     success_url = reverse_lazy('tvasahi:tv_detail')
#
#     def get_success_url(self):
#         return resolve_url('tvasahi:tv_detail', pk=self.kwargs['pk'])

class CommentDeleteView(generic.DeleteView):
    model = Comment
    success_url = reverse_lazy('tvasahi:tv_detail')

    def get_success_url(self):
        return resolve_url('tvasahi:tv_detail', self.object.target.pk)


class SearchView(generic.ListView):
    model = Tv
    template_name = 'tvasahi/tv_search.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        form = SearchForm(self.request.GET)
        form.is_valid()

        # self.request.GET で値の保持が実行される
        context['form'] = form
        category_value = form.cleaned_data.get('category')
        favorite_category_value = form.cleaned_data.get('favorite_category')

        if category_value:
            context['category_value'] = category_value.id

        if favorite_category_value:
            context['favorite_category_value'] = category_value.id

        return context

    # 条件検索
    def get_queryset(self):

        queryset = super().get_queryset()
        form = SearchForm(self.request.GET)
        form.is_valid()

        keyword = form.cleaned_data.get('keyword')
        category = form.cleaned_data.get('category')

        if keyword:
            queryset = queryset.filter(
                Q(program_name__icontains=keyword) | Q(content__icontains=keyword)
            )

        if category:
            queryset = queryset.filter(category=category)

        return queryset


class Login(LoginView):
    template_name = 'tvasahi/login.html'

    def form_invalid(self, form):
        messages.error(self.request, 'ログインに失敗しました。正しいユーザー名とパスワードを入力してください。')
        return super().form_invalid(form)


class Logout(LogoutView):
    template_name = 'tvasahi/logout.html'

    def get(self, request):
        logout(request)
        messages.success(request, 'ログアウトしました。')
        return redirect('tvasahi:home')


class CustomUserCreationView(generic.CreateView):
    Model = CustomUser
    form_class = CustomUserCreationForm
    template_name = 'tvasahi/user_create.html'
    success_url = reverse_lazy('tvasahi:home')

    def form_valid(self, form):
        response = super().form_valid(form)
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password=password)
        login(self.request, user)
        return response


# 自分しかアクセスできないようにする
class OnlyYouMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        # 今ログインしてるユーザーのpkと、そのマイページのpkが同じなら許可
        user = self.request.user
        return user.pk == self.kwargs['pk']


# マイページ
# class MyPage(OnlyYouMixin, generic.DetailView):
#     model = CustomUser
#     template_name = 'tvasahi/mypage.html'
#     # モデル名小文字(user)でモデルインスタンスがテンプレートファイルに渡される
#
#     @login_required
#     def mypage_view(request):
#         customuser = request.customuser  # ログイン中のCustomUserオブジェクトを取得
#         context['comment_list'] = Comment.objects.filter(user_name=customuser)
#         # 他のコードやレンダリングなどの処理
#
#         return render(request, 'mypage.html', context)


class MyPage(OnlyYouMixin, generic.DetailView):
    model = CustomUser
    template_name = 'tvasahi/mypage.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_list'] = Comment.objects.filter(user_name=self.request.user)
        # 他のコードやレンダリングなどの処理
        return context

class CommentDeleteView2(generic.DeleteView):
    model = Comment
    success_url = reverse_lazy('tvasahi:mypage')

    def get_success_url(self):
        return resolve_url('tvasahi:mypage', self.request.user.pk)


class UserUpdate(OnlyYouMixin, generic.UpdateView):
    model = CustomUser
    form_class = UserUpdateForm
    template_name = 'tvasahi/user_update.html'

    def get_success_url(self):
        return resolve_url('tvasahi:mypage', pk=self.kwargs['pk'])


class CustomUserDeleteView(generic.DeleteView):
    template_name = 'tvasahi/user_delete.html'
    model = CustomUser
    success_url = reverse_lazy('tvasahi:home')

tv_listing/templates/tvasahi/mypage.html
{%  extends 'base.html' %}
{% block content %}

<h2>マイページ</h2>
<style>
    .parent{
    display: grid;
    grid-template-columns: 1fr 0.2fr;
    column-gap: 20px;
    }
    .icon{
    border: solid 5px #FF0099
    }

<!--コメント欄のcss-->
    .search_button{
          cursor: pointer;
          width: 50px;
          height: 25px;
          border: none;
          padding: 0.5em 1em;
          text-decoration: none;
          background: #ff0099;
          color: #FFF;
          border-radius: 3px;
    }
    .search_button:active{
          box-shadow:inset -2px -2px 3px rgba(255, 255, 255, .6),
          inset 2px 2px 3px rgba(0, 0, 0, .6);
    }
    .search_button:hover{
        background-color: #c71585;
    }
    .comment_child{
        font-weight: bolder;
        vertical-align: middle;
        padding-bottom: 0px;
        margin-bottom: 0px;
        margin-top: 0px;
	}



</style>
    <div class="parent">
    <div class="child">
    <table class="detail">
        <tr>
            <th >ユーザー名</th>
            <td style="font-weight: 500;">{{ customuser.username }}</td>
        </tr>
    </table>
    <table class="detail">
        <tr>
            <th>メールアドレス</th>
            <td style="font-weight: 500;">{{ customuser.email }}</td>
        </tr>
    </table>
    <table class="detail">
        <tr>
            <th>住所</th>
            <td style="font-weight: 500;">{{ customuser.address }}</td>
        </tr>
    </table>
    <table class="detail">
        <tr>
            <th>好きな番組ジャンル</th>
            <td style="font-weight: 500;">{{ customuser.favorite_category }}</td>
        </tr>
    </table>
    </div>
    <div class="child">
        {% if customuser.icon %}
            <img class="icon" src="{{ customuser.icon.url }}" width="200px" height="190px">
        {% else %}
            <img src="../../../static/picture/noimage.png" alt="noimage" width="200x" height="190px">
        {% endif %}
    </div>
    </div>

<br>


<div class="" style="display: flex; justify-content: space-around;">
    <a href="{% url 'tvasahi:user_update' customuser.pk %}" class="btn btndetail">更新ページへ</a>
    <a href="#" onclick="msgdsp1(); return false;" class="btn btndetail">ログアウト</a>
    <form name="delete" method="post" action="{% url 'tvasahi:user_delete' customuser.pk %}">
        {% csrf_token %}
        <input type="hidden" class="btn btn-danger" onclick="msgdsp2(); return false;" >
        <a href="{% url 'tvasahi:user_delete' customuser.pk %}" onclick="msgdsp2(); return false;" class="btn btndetail">削除</a>
    </form>
</div>
<br><br>

<h2>投稿コメント一覧</h2>

{% if comment_list %}
    {% for comment in comment_list %}
    <div style="border: solid 1px; border-radius: 5px; padding: 5px; margin: 0px;">
        {% if comment.target.url == null %}
        <p class="comment_child">{{ comment.target.date }} {{ comment.target.get_time_hour_and_minute }}放送  『{{ comment.target.program_name }}』</p>
        <p style="font-size: 10px; padding-top: 0px; margin-top: 0px;">{{ comment.pub_date|date:"Y/m/d(D) H:i:s" }} 投稿</p>
            {{ comment }}
        {% else %}
        <p class="comment_child">{{ comment.target.date }} {{ comment.target.get_time_hour_and_minute }}放送  <a href="{{ comment.target.url }}">『{{ comment.target.program_name }}』</a></p>
        <p style="font-size: 10px; padding-top: 0px; margin-top: 0px;">{{ comment.pub_date|date:"Y/m/d(D) H:i:s" }} 投稿</p>
            {{ comment }}
        {% endif %}

        <form name="comment_delete" method="post" action="{% url 'tvasahi:comment_delete2' comment.pk %}">
                {% csrf_token %}

                <button type="button" class="search_button"  style="border: none; width: 50px; height: 25px;" onclick="msgdsp3('{{ comment.pk }}')" >削除</button>

        </form>
    </div>
    <br>
    {% endfor %}
{% else %}
    過去のコメントはありません
{% endif %}

{% endblock %}

{% block extra_js %}
  <script>
    function msgdsp1() {
      var confirmLogout = confirm('本当にログアウトしますか？');
      if (confirmLogout) {
        window.location.href = "{% url 'tvasahi:logout' %}";
      }
    }
  </script>

  <script>
    function msgdsp2(){
    var confirmDelete = confirm('本当にアカウントを削除しますか？');
      if (confirmDelete) {
        document.delete.submit() ;
      }
    }
  </script>

  <script>
    function msgdsp3(pk){
    var confirmDelete = confirm('本当にコメントを削除しますか？');
      if (confirmDelete) {
        const form = document.getElementsByName('comment_delete')[0]
        form.action = '/comment_delete2/' + pk + '/';
        form.submit() ;
      }
    }
  </script>
{% endblock %}

tv_listing/templates/tvasahi/mypage_back.html
{%  extends 'base.html' %}
{% block content %}

<h2>マイページ</h2>
    <table class="detail">
        <tr>
            <th>ユーザー名</th>
            <td>{{ customuser.username }}</td>
        </tr>
    </table>
    <table class="detail">
        <tr>
            <th>メールアドレス</th>
            <td>{{ customuser.email }}</td>
        </tr>
    </table>
    <table class="detail">
        <tr>
            <th>住所</th>
            <td>{{ customuser.address }}</td>
        </tr>
    </table>
    <table class="detail">
        <tr>
            <th>好きな番組ジャンル</th>
            <td>{{ customuser.favorite_category }}</td>
        </tr>
    </table>

<!--    {% for comment in comment_list %}-->
<!--    <div>-->
<!--        {{ tv.get_time_hour_and_minute }}-->
<!--        {% if tv.url == null %}-->
<!--            {{ tv.program_name }}-->
<!--        {% else %}-->
<!--            <a href="{{ tv.url }}">{{ tv.program_name }}</a>-->
<!--        {% endif %}-->
<!--        &lt;!&ndash;　<button onclick="location.href='{% url "tvasahi:tv_detail" tv.pk %}'" type="submit">詳細ページ</button>&ndash;&gt;-->
<!--        <a href="{% url 'tvasahi:tv_detail' tv.pk %}">詳細ページ</a>-->
<!--    </div>-->
<!--    <br>-->
<!--  {% endfor %}-->

<br>


<div class="btn btndetail" style="display: flex; justify-content: space-around;">
    <a href="{% url 'tvasahi:user_update' customuser.pk %}" >更新ページへ</a>
    <a href="#" onclick="msgdsp1(); return false;">ログアウト</a>
    <form name="delete" method="post" action="{% url 'tvasahi:user_delete' customuser.pk %}">
        {% csrf_token %}
        <input type="hidden" class="btn btn-danger" onclick="msgdsp2(); return false;" >
        <a href="{% url 'tvasahi:user_delete' customuser.pk %}" onclick="msgdsp2(); return false;" class="btn btn-danger">削除</a>
    </form>
</div>



{% endblock %}

{% block extra_js %}
  <script>
    function msgdsp1() {
      var confirmLogout = confirm('本当にログアウトしますか？');
      if (confirmLogout) {
        window.location.href = "{% url 'tvasahi:logout' %}";
      }
    }
  </script>

  <script>
    function msgdsp2(){
    var confirmDelete = confirm('本当に削除しますか？');
      if (confirmDelete) {
        document.delete.submit() ;
      }
    }

  </script>
{% endblock %}

tv_listing/templates/tvasahi/tv_detail.html
{% extends 'base.html' %}

{% block content %}

<style>
    .delete_button{
          cursor: pointer;
          width: 60px;
          height: 30px;
          border: none;
          padding: 0.5em 1em;
          text-decoration: none;
          background: #ff0099;
          color: #FFF;
          border-radius: 3px;
    }
    .delete_button:active{
          box-shadow:inset -2px -2px 3px rgba(255, 255, 255, .6),
          inset 2px 2px 3px rgba(0, 0, 0, .6);
    }
    .delete_button:hover{
      background-color: #c71585;
    }
    h4{
	font-weight: bolder;
	vertical-align: middle;
	padding-bottom: 0px;
	margin-bottom: 0px;
	margin-top: 0px;
	}
	h4 img{
	vertical-align: middle;
	}

</style>

    <h1>番組詳細</h1>

    <table class="detail">
        <tr>
            <th>放送日</th>
            <td>{{ tv.date.on_air_date }}</td>
        </tr>
        <tr>
            <th>放送時間</th>
            <td>{{ tv.get_time_hour_and_minute }}</td>
        </tr>
        <tr>
            <th>タイトル</th>
            <td>{{ tv.program_name }}</td>
        </tr>
        <tr>
            <th>番組内容</th>
            <td>{{ tv.content }}</td>
        </tr>
        <tr>
            <th>カテゴリ</th>
            <td>{{ tv.category }}</td>
        </tr>
    </table>

<br>

    <div class="btn back">
        <a href="{% url 'tvasahi:tv_list' tv.date.pk %}">番組一覧へ戻る</a>
    </div>

    <h1>コメント欄</h1>
    {% for comment in tv.comment_set.all %}
        <div style="border: solid 1px; border-radius: 5px; padding: 5px; margin: 5px;">
            <h4 class="comment_child"><img src="{{ comment.user_name.icon.url }}" width="25px" height="25px" alt="アイコン" style="border-radius: 10px;">{{ comment.user_name.username }}</h4>
            <p class="comment_child" style="font-size: 10px; padding-top: 0px; margin-top: 0px;">{{ comment.pub_date|date:"Y/m/d(D) H:i:s" }}</p>

            <div>
                <p>{{ comment.comment | linebreaks }}</p>
            </div>

            {% if comment.user_name.username == user.username %}
                <form name="delete{{ comment.pk }}" method="post" action="{% url 'tvasahi:comment_delete' comment.pk %}">
                    {% csrf_token %}

                    <input class="delete_button" type="button"  onclick="msgdsp('delete{{ comment.pk }}')" value="削除">

                </form>
            {% endif %}
        </div>
    {% endfor %}

    <div class="btn btndetail">
        <a href="{% url 'tvasahi:comment_create' tv.id %}">コメント投稿</a>
    </div>



{% endblock %}

{% block extra_js %}

  <script>
    function msgdsp(name){
    var confirmDelete = confirm('本当に削除しますか？');
      if (confirmDelete) {
        const form = document.getElementsByName(name)[0]
        form.submit()
      }
    }

  </script>
{% endblock %}

tv_listing/templates/tvasahi/tv_list.html
{% extends 'base.html' %}
{% block content %}

    {% for tv in tv_list|slice:":1" %}
        <h1>{{ tv.date.on_air_date }} 番組一覧</h1>
    {% endfor %}

<div style="display: grid; justify-items: center; grid-template-columns: 1fr 1fr 1fr 1fr 1fr 1fr 1fr; overflow: scroll;" >
   {% for date in date_list %}
    <div class="home">
        <input type="radio"><a href="{% url 'tvasahi:tv_list' date.pk %}" style="color: inherit; text-decoration: none;">{{ date.on_air_date }}</a>
    </div>
    {% endfor %}
</div>

    {% for tv in tv_list %}
    <table class="list">
        <tr class="name-hover">
            <th>{{ tv.get_time_hour_and_minute }}</th>
            {% if tv.url == null %}
                <td>{{ tv.program_name }}</td>
            {% else %}
                <td><a href="{{ tv.url }}" target="_blank" style="color: inherit; text-decoration: none;">{{ tv.program_name }}</a></td>
            {% endif %}
            <!--　<button onclick="location.href='{% url "tvasahi:tv_detail" tv.pk %}'" type="submit">詳細ページ</button>-->
                <td><a class="white-link btn btndetail" href="{% url 'tvasahi:tv_detail' tv.pk %} ">詳細ページ</a></td>
        </tr>
    </table>
  {% endfor %}

    <div class="btn back" style="margin: 50px 0px 0px 0px;">
        <a href="{% url 'tvasahi:home' %}">番組一覧へ戻る</a>
    </div>


{% endblock %}