tv_listing/conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tvasahi.urls')),
    path('store/', include('store.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tv_listing/store/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required


app_name = 'store'

urlpatterns = [
    path('home/', views.Home.as_view(), name='home'),
    path('detail/<int:pk>/', login_required(views.GoodsDetail.as_view()), name='detail'),
    path('add_sessioncart/', views.SessionAddToCart.as_view(), name='add_sessioncart'),
    path('sessioncontent/', views.SessionCartContent.as_view(), name='sessioncart_content'),
    path('add_modelcart/', views.ModelAddToCart.as_view(), name='add_modelcart'),
    path('modelcontent/<int:pk>/', views.ModelCartContent.as_view(), name='modelcart_content'), # pk は CartUnitのpk
    path('delete_modelcart/', views.ModelCartDelete.as_view(), name='modelcart_delete'),
    path('delete_sessioncart/', views.SessionCartDelete.as_view(), name='sessioncart_delete'),
    path('purchase/preview/', views.PurchasePreview.as_view(), name='purchase_preview'),
    path('purchase/_process/', views.PurchaseProcess.as_view(), name='_purchase_process'),
    path('purchase/done/', views.PurchaseDone.as_view(), name='purchase_done'),
]

tv_listing/tvasahi/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required


app_name = 'tvasahi'

urlpatterns = [
    path('home/', views.Home.as_view(), name='home'),
    path('tvlist/<int:pk>/', views.TvListView.as_view(), name='tv_list'),
    path('tvdetail/<int:pk>/', views.TvDetailView.as_view(), name='tv_detail'),
    path('tvsearch/', views.SearchView.as_view(), name='tv_search'),
    path('comment_create/<int:pk>/', login_required(views.CommentCreateView.as_view()), name='comment_create'),
    path('login/', views.Login.as_view(), name='login'),
    path('user_create/', views.CustomUserCreationView.as_view(), name='user_create'),
    path('mypage/<int:pk>/', views.MyPage.as_view(), name='mypage'),
    path('user_update/<int:pk>/', views.UserUpdate.as_view(), name='user_update'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('user_delete/<int:pk>/', views.CustomUserDeleteView.as_view(), name='user_delete'),
    path('comment_delete/<int:pk>/', views.CommentDeleteView.as_view(), name='comment_delete'),
    path('comment_delete2/<int:pk>/', views.CommentDeleteView2.as_view(), name='comment_delete2')

    ]

tv_listing/store/models.py
from django.core.validators import MinValueValidator
from tvasahi.models import CustomUser
from django.utils import timezone
from django.db import models
from django.core.validators import MaxValueValidator


# Create your models here.
class Goods(models.Model):
    name = models.CharField('商品名', unique=True, max_length=100)
    price = models.PositiveIntegerField('価格', validators=[MaxValueValidator(1000000000)])
    description = models.TextField('商品説明')
    # FileField→ファイルなんでもアップロードできるフィールド
    # ImageField→画像アップロード用のフィールド
    image = models.ImageField('商品画像', null=True, blank=True, upload_to='goods_images/')

    def __str__(self):
        return self.name


class CartUnit(models.Model):
    """Cartに格納される最小単位"""
    goods = models.ForeignKey(to=Goods, verbose_name='書籍', on_delete=models.CASCADE, blank=False)
    quantity = models.PositiveIntegerField('購入数', default=1, blank=False, validators=[MinValueValidator(1, )])

    def __str__(self):
        return '{}:{}'.format(self.goods.name, self.quantity)


class Cart(models.Model):
    units = models.ManyToManyField(to=CartUnit, verbose_name=' ユニット', blank=True)

    @property
    def total_price(self):
        """:returns total price of goodss in a cart"""
        each_goodss_price = [unit.goods.price * unit.quantity for unit in self.units.all()]
        return sum(each_goodss_price)

    def add_unit(self, unit_add):
        """CartUnitをカートに追加する際に呼び出す。
        既に同じ種類の本がカートに存在する際は、個数を足し算するようにする。
        """
        if unit_add.goods in [unit.goods for unit in self.units.all()]:
            unit_origin = self.units.get(goods_id=unit_add.goods.id)
            unit_origin.quantity += unit_add.quantity
            unit_origin.save()
        else:
            unit_add.save()
            self.units.add(unit_add)

    def _add_session_unit(self, goods_pk, quantity):
        """Session CartのカートユニットをModel CartのCartUnitに変換した上で、追加する。
        既に同じ種類の本がカートに存在する際は、個数を足し算するようにする。
        """
        goods_pk = int(goods_pk)
        if goods_pk in [unit.goods.pk for unit in self.units.all()]:
            unit_origin = self.units.get(goods_id=goods_pk)
            unit_origin.quantity += quantity
            unit_origin.save()
        else:
            unit_add = CartUnit(goods=Goods.objects.get(pk=goods_pk), quantity=quantity)
            unit_add.save()
            self.units.add(unit_add)

    def import_session(self, session_cart):
        """Session Cartの中身をすべてモデルカートに移す"""
        for cart_unit in session_cart:
            self._add_session_unit(cart_unit['goods_pk'], cart_unit['quantity'])

    def __str__(self):
        # print(self.customuser)
        if hasattr(self, 'customuser'):
            return "{}'s model cart".format(self.customuser.username)

        else:
            return 'まだ紐づいていません'



class Purchase(models.Model):
    fk_user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.PROTECT)
    fk_goods = models.ForeignKey(Goods, verbose_name='書籍', on_delete=models.PROTECT)
    purchase_time = models.DateTimeField('購入時刻', default=timezone.now)
    purchase_num = models.PositiveIntegerField('購入数', blank=False, validators=[MaxValueValidator(10), ])
    state_flag = models.BooleanField('運用状況', default=True)

    def __str__(self):
        return str(self.fk_user) + ':' + str(self.fk_goods)

tv_listing/store/forms.py
from django import forms
from .models import CartUnit


class GoodsSearchForm(forms.Form):
    name = forms.CharField(max_length=128)


class CartUnitForm(forms.ModelForm):
    class Meta:
        model = CartUnit
        fields = ('quantity',)

tv_listing/store/views.py
from .forms import GoodsSearchForm, CartUnitForm
from django.contrib.auth.mixins import LoginRequiredMixin
from .helper import OnlyYouMixin, PostOnlyYouMixin, GetOnlyYouMixin, PostOnlyYouMixin, SessionCartManager
from tvasahi.models import CustomUser
from .models import Goods, CartUnit, Purchase
from django import forms
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import generic
from django.views.decorators.cache import never_cache
from django.views.generic.edit import ModelFormMixin
from .models import Cart


class Home(generic.ListView):
    model = Goods
    template_name = 'store/home.html'
    form_class = GoodsSearchForm
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(generic.ListView, self).get_context_data(**kwargs)
        context.update(dict(form=self.form_class, query_string=self.request.GET.urlencode()))

        q_name = self.request.GET.get('name')

        context['form'] = GoodsSearchForm(initial={
            'name': q_name,})

        return context

    def get_queryset(self):
        goodss = Goods.objects.all()
        q_name = self.request.GET.get('name')

        if q_name:
            goodss = goodss.filter(name__icontains=q_name)

        return goodss


class GoodsRank(generic.ListView):
    model = Goods
    template_name = 'tvasahi/home.html'

    def get_queryset(self):
        goodss = Goods.objects.all()
        q_name = self.request.GET.get('name')

        if q_name:
            goodss = goodss.filter(name__icontains=q_name)

        return goodss


@method_decorator(never_cache, name='dispatch')
class ModelCartContent(OnlyYouMixin, generic.DetailView):
    model = CustomUser
    context_object_name = 'cart'
    template_name = 'store/contents.html'

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        return obj.cart


class ModelAddToCart(LoginRequiredMixin, generic.RedirectView):
    """CartUnitをカートに追加する。
    どのユーザのカートの追加するかは、サーバ側で決定しているので、OnlyYouMixinはいらない
    """

    def get_redirect_url(self):
        user_pk = self.request.user.pk
        return reverse_lazy('store:modelcart_content', args=(user_pk,))

    def post(self, request, *args, **kwargs):
        user = request.user

        if not user.cart:
            user.cart = Cart.objects.create()
            user.save()

        goods_pk = request.POST['goods_pk']
        quantity = request.POST['quantity']
        user.cart.add_unit(CartUnit(goods=Goods.objects.get(pk=goods_pk), quantity=int(quantity)))
        return super().post(request, *args, **kwargs)


class ModelCartDelete(PostOnlyYouMixin, generic.DeleteView):
    """
    CartUnitをカートに追加する。
    """
    model = CartUnit

    def get_object(self, queryset=None):
        unit_pk = self.request.POST['unit_pk']
        return CartUnit.objects.get(id=unit_pk)

    def get_success_url(self):
        user_pk = self.request.user.pk
        return reverse_lazy('store:modelcart_content', args=(user_pk,))


@method_decorator(never_cache, name='dispatch')
class PurchasePreview(GetOnlyYouMixin, generic.TemplateView):
    template_name = 'store/preview.html'

    def get_context_data(self, **kwargs):
        cart = self.request.user.cart
        ctx = super().get_context_data(**kwargs)
        ctx['total_price'] = cart.total_price
        return ctx


@method_decorator(never_cache, name='dispatch')
class PurchaseProcess(PostOnlyYouMixin, generic.FormView):
    """
    TemplateView ではpostは未実装。
    djangoのformは使わない
    """
    form_class = forms.Form
    success_url = reverse_lazy('store:purchase_done')

    def form_valid(self, form):
        user = self.request.user

        for unit in user.cart.units.all():
            Purchase.objects.create(fk_user=user, fk_goods=unit.goods, purchase_num=unit.quantity)
        user.cart.units.clear()
        return super().form_valid(form)


class PurchaseDone(generic.TemplateView):
    template_name = 'store/done.html'


@method_decorator(never_cache, name='dispatch')
class SessionCartContent(generic.TemplateView):
    template_name = 'store/contents.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data()
        cart = self.request.session.get(SessionCartManager.kname, [])
        ctx['lis_cart'] = SessionCartManager.to_rendered(cart)
        return ctx


class SessionAddToCart(generic.RedirectView):
    url = reverse_lazy('store:sessioncart_content')

    def post(self, request, *args, **kwargs):
        goods_pk = request.POST['goods_pk']
        quantity = request.POST['quantity']
        cart = request.session.get(SessionCartManager.kname, [])
        cart = SessionCartManager.add_unit(cart, goods_pk, quantity)
        request.session[SessionCartManager.kname] = cart
        return super().post(request, *args, **kwargs)


class SessionCartDelete(generic.FormView):
    form_class = forms.Form
    success_url = reverse_lazy('store:sessioncart_content')

    def form_valid(self, form):
        cart = self.request.session[SessionCartManager.kname]
        deleting_goods_pk = int(self.request.POST['goods_pk'])
        cart = SessionCartManager.delete_unit(cart, deleting_goods_pk)
        self.request.session[SessionCartManager.kname] = cart
        return super().form_valid(form)


class GoodsDetail(ModelFormMixin, generic.DetailView):
    model = Goods
    template_name = 'store/detail.html'
    context_object_name = 'goods'
    form_class = CartUnitForm

    def form_valid(self, form):
        return render(self.request, 'store/detail.html', {'form': form})

tv_listing/templates/store/contents.html
{% extends 'base2.html' %}


{% block content %}
{% if user.is_authenticated %}
<h2>ショッピングカート</h2>
{% if cart.units.all %}
<table style="display: flex; justify-content: space-around;">
    <tr>
        <th>商品</th>
        <th>数量</th>
    </tr>
    {% for unit in cart.units.all %}
    <tr>
        <th>{{ unit.goods }}</th>
        <th>{{ unit.quantity }}</th>
        <td style="padding: 0px 0px 0px 40px;">
            <form method="post" action="{% url 'store:modelcart_delete' %}">{% csrf_token %}
                <input type="hidden" name="unit_pk" value="{{ unit.pk }}">
                <input type="hidden" name="uname" value="{{ user.username }}">
                <input type="submit" class="search_button_blue" style="border:none;" value="削除">
            </form>
        </td>
    </tr>

    {% endfor %}
</table>
<br>
<div style="display: flex; justify-content: space-around;">

    <div>
        <a href="{% url 'store:home' %}" class="btn_ec back_ec">買い物を続ける</a>
    </div>

    <form action="{% url 'store:purchase_preview' %}" method="get">
        <input type="hidden" name="uname" value="{{ user.username }}">
        <button type="submit" class="btn_ec btndetail_ec" style="border:none;">購入画面へ</button>
    </form>

</div>

{% else %}
<p>カートは空です。</p>
<br>
    <div>
        <a href="{% url 'store:home' %}" class="btn_ec back_ec">トップへ</a>
    </div>
{% endif %}
{% else %}
{% if lis_cart %}
<table style="display: flex; justify-content: space-around;">
    <tr>
        <th>{{ unit.goods }}</th>
        <th>{{ unit.quantity }}</th>
    </tr>
    {% for unit in lis_cart %}
    <tr>
        <th>{{ unit.goods }}</th>
        <th>{{ unit.quantity }}</th>
        <td style="padding: 0px 0px 0px 40px;">
            <form method="post" action="{% url 'store:sessioncart_delete' %}">{% csrf_token %}
                <input type="hidden" name="goods_pk" value="{{ unit.goods_pk }}">
                <input type="submit" value="削除">
            </form>
        </td>
    </tr>
    {% endfor %}
</table>

<div style="display: flex; justify-content: space-around;">

    <div>
        <a href="{% url 'store:home' %}" class="btn_ec back_ec">買い物を続ける</a>
    </div>

    <form action="{% url 'tvasahi:login' %}" method="get">
        <input type="hidden" name="next_page" value="purchase"><a href="#" class="btn_ec btndetail_ec">購入画面へ</a>
        <button type="submit" class="btn_ec btndetail_ec" style="border:none;">購入画面へ</button>
    </form>

</div>


{% else %}
カートは空です。
    <div class="btn_ec btndetail_ec">
        <a href="{% url 'store:home' %}">トップへ</a>
    </div>
{% endif %}
{% endif %}

{% endblock %}

tv_listing/templates/store/detail.html
{% extends 'base2.html' %}

{% block content %}
<table class="ec-detail">
    <tr>
        <th>
            <img src="{{ goods.image.url }}" style="max-width: 100%; max-height: 150px;"/>
        </th>
        <td class="ec-detail-css">
            <table>
                <tr>
                    <td style="font-weight: bold;">{{ goods.name }}</td>
                </tr>
                <tr>
                    <td>価格：{{ goods.price }}円</td>
                </tr>
                <tr>
                    <td>{{ goods.description }}</td>
                </tr>
            </table>
        </td>
    </tr>
</table>

<br>
{% if user.is_authenticated %}
<form action="{% url 'store:add_modelcart' %}" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div style="display: grid; justify-items: center; grid-template-columns: 1fr 1fr 1fr; align-items: center;" >
        <a href="{% url 'store:home' %}" class="btn_ec back_ec">トップへ</a>
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
            {{ field }}
            {{ field.errors }}
        </div>
        {% endfor %}
        {% csrf_token %}
        <input type="hidden" name="goods_pk" value="{{ goods.pk }}">
        <button type="submit" class="btn_ec btndetail_ec" style="border:none;">追加</button>
    </div>
</form>
{% else %}
<form action="{% url 'store:add_sessioncart' %}" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div style="display: flex; justify-content: center;">
        <a href="{% url 'store:home' %}" class="btn_ec back_ec">トップへ</a>
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
            {{ field }}
            {{ field.errors }}
        </div>
        {% endfor %}
        {% csrf_token %}
        <input type="hidden" name="goods_pk" value="{{ goods.pk }}">
        <a href="{% url 'store:home' %}" class="btn_ec back_ec">トップへ</a>
        <button type="submit" class="btn_ec btndetail_ec" style="border:none;">追加</button>
    </div>
</form>
　　{% endif %}
{% endblock %}

tv_listing/templates/store/done.html
{% extends 'base2.html' %}

{% block content %}
<br>
    <div style="display: flex; justify-content: center;">
    <img src="../../../static/picture/done.png" alt="感謝" width="700px"></a>
<!--    <div style="display: flex; justify-content: space-around; font-weight: bold;">-->
<!--        購入手続きが完了しました。お買い上げありがとうございます。-->
    </div>

<br>

    <div style="display: flex; justify-content: center;">
        <a href="{% url 'store:home' %}" class="btn_ec back_ec">トップへ</a>
    </div>

{% endblock %}

tv_listing/templates/store/home.html
{% extends 'base2.html' %}

{% block content %}
<h2>商品リスト</h2>
<style>
    .parent{
        display: flex;
        flex-wrap: wrap;
    }

    .parent .no-results p,
    .parent .no-results .btn_ec {
        text-align: center;
        padding:5px
    }

    .child{
        padding: 10px;
        width: 250px;
    }

</style>
<div style="display: flex; justify-content: space-around;">

    <form action="" method="get" id="GoodsSearchForm">
        <div style="display: flex; justify-content: center;">
            <label class="search-form-blue" style="">
                <input name="name" type="text" placeholder="キーワードを入力" value="{{ form.cleaned_data.name }}">
            </label>
            <button type="submit" class="search_button_blue" style="border:none; margin: 2px 0px 0px 2px;">検索</button>
        </div>
    </form>

</div>


<div class="parent">
<!--    <ul style="list-style: none;">-->
    {% if goods_list %}
        {% for goods in goods_list %}
            <div class="child" >
                <a class="ec-name" href="{% url 'store:detail' goods.pk %}">{{ goods.name }} </a>
                <p>{{ goods.price }}円</p>
                <a href="{% url 'store:detail' goods.pk %}">
                    <img src="{{ goods.image.url }}" style="max-width: 100%; max-height: 150px;"/>
                </a>
            </div>
        {% endfor %}
<!--    </ul>-->

</div>

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?{{ query_string }}&page={{ page_obj.previous_page_number }}">前のページへ</a>
        {% endif %}

        {% for link_page in page_obj.paginator.page_range %}
        {% if link_page == page_obj.number %}
            <span class="page-link" href="#">{{ link_page }}</span>
        {% else %}
           <span class="page-link" href="#"><a
                   href="?{{ query_string }}&page={{ link_page }}">{{ link_page }}</a></span>
        {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a href="?{{ query_string }}&page={{ page_obj.next_page_number }}">次のページへ</a>
        {% endif %}
    </span>
</div>
{% else %}
        <div class="no-results">
            <p style="text-align: center;">検索に該当する商品は存在しませんでした</p>
            <div>
                <a style="text-align:right" href="{% url 'store:home' %}" class="btn_ec back_ec">トップへ</a>
            </div>
        </div>

{% endif %}

{% endblock %}

tv_listing/templates/store/preview.html
{% extends 'base2.html' %}

{% block content %}
<h1 style="display: flex; justify-content: space-around;">購入内容</h1>
   <table style="display: flex; justify-content: space-around;">
        <tr>
            <th style="text-align: center;">商品</th>
            <th style="text-align: center;">数量</th>
        </tr>
        {% for cartunit in user.cart.units.all %}
            <tr>
                <th style="text-align: center;">{{ cartunit.goods }}</th>
                <th style="text-align: center;">{{ cartunit.quantity }}</th>
            </tr>
        {% endfor %}
    </table>

    <h1 style="display: flex; justify-content: space-around;">請求額</h1>
    <div style="display: flex; justify-content: space-around; font-weight: bold;">{{ total_price }}円</div>

    <h1 style="display: flex; justify-content: space-around;">配送先</h1>
    <div style="display: flex; justify-content: space-around; font-weight: bold;">{{ user.address }}</div>
<br><br><br>
    <div style="display: flex; justify-content: space-around;">
        <form action="{% url 'store:_purchase_process' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="uname" value="{{ user.username }}">
            <button type="submit" class="btn_ec btndetail_ec" style="border:none;">購入確定</button>
        </form>
    </div>
{% endblock %}